version: '3'
services:
  notebook:
    # image: pbatey/jupyter-datascience-notebook-gpu:2021apr07
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/home/jovyan/workspace
      - ../:/home/jovyan/work
      - type: bind
        source: /home/allenyl/.ssh
        target: /home/jovyan/.ssh_host
    ports:
      - 0.0.0.0:8900:8888
      # - 8501:8501
    # enable passwordless sudo
    # environment:
    #   - GRANT_SUDO=yes
    # user: root
    command:
      /home/jovyan/workspace/.devcontainer/library-scripts/setup.sh
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
